Coffee/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Coffee.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Order> Orders { get; set; }
    }
}

Coffee/Models/Comment.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Coffee.Models
{
    public class Comment
    {
        [BindNever]
        public int CommentId { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите имя")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите телефон")]
        public int Phone { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите комментарий")]
        public string Text { get; set; }
    }
}

Coffee/Models/EFDataRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Coffee.Models
{
    public class EFDataRepository : IDataRepository
    {
        private ApplicationDbContext context;
        public EFDataRepository(ApplicationDbContext ctx)
        {
            context = ctx;
        }
        public IQueryable<Comment> Comments => context.Comments;
        public IQueryable<Order> Orders => context.Orders;

        public void SaveOrder (Order order)
        {
            if(order.OrderId == 0)
            {
                context.Orders.Add(order);
            }
            context.SaveChanges();
        }

        public void SaveComment(Comment comment)
        {
            if(comment.CommentId == 0)
            {
                context.Comments.Add(comment);
            }
            context.SaveChanges();
        }
    }
}

Coffee/Models/IDataRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Coffee.Models
{
    public interface IDataRepository 
    {
        IQueryable<Comment> Comments { get; }
        IQueryable<Order> Orders { get; }
        void SaveOrder(Order order);
        void SaveComment(Comment comment);
    }
}

Coffee/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Coffee.Models
{
    public class Order
    {
        [BindNever]
        public int OrderId { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите имя")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите номер телефона")]
        public int Phone { get; set; }
    }
}

Coffee/Models/SeedData.cs
using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Coffee.Models
{
    public static class SeedData
    {
        public static void EnsurePopulated(IApplicationBuilder app)
        {
            ApplicationDbContext context = app.ApplicationServices
                .GetRequiredService<ApplicationDbContext>();
            context.Database.Migrate();
            if (!context.Comments.Any())
            {
                context.Comments.AddRange(
                        new Comment
                        {
                            Name = "TestName",
                            Phone = 1245678,
                            Text = "Sample text"

                        }
                    );

                context.SaveChanges();
            }
        }
    }
}

Coffee/Controllers/CommentController.cs
using Coffee.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Coffee.Controllers
{
    public class CommentController : Controller
    {
        private IDataRepository repository;
        public CommentController(IDataRepository repoService)
        {
            repository = repoService;
        }
        public ViewResult Add() => View(new Comment());
        [HttpPost]
        public IActionResult Add(Comment comment)
        {
            if (ModelState.IsValid)
            {
                repository.SaveComment(comment);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(comment);
            }
        }
        public ViewResult Completed()
        {
            return View();
        }
    }
}

Coffee/Controllers/HomeController.cs
using Coffee.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Coffee.Controllers
{
    public class HomeController : Controller
    {
        private IDataRepository repository;
        public HomeController(IDataRepository repoService)
        {
            repository = repoService;
        }
        public ViewResult Index()
        {
            return View(new Order());
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (ModelState.IsValid)
            {
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }
        public ViewResult Completed()
        {
            return View();
        }
        public IActionResult CommentsPartial()
        {
            var listComments = repository.Comments.ToList();
            return PartialView(listComments);
        }
    }
}

Coffee/Views/Comment/Add.cshtml
@{
    ViewData["Title"] = "Add Comment";
    Layout = "~/Views/_Layout.cshtml";
}
@model Comment

<section class="order" id="order">
    <div class="container order_container">
        <img src="~/img/order_bg.jpg" alt="" class="orger_img">
        <form asp-controller="Comment" asp-action="Add" method="post" class="order_form">
            <h3 class="text order_form_heading">Оставить комментарий</h3>

            <input asp-for="Name" type="text" placeholder="Имя" class="text order_input">
            <input asp-for="Phone" type="number" placeholder="Номер телефона" class="text order_input">
            <input asp-for="Text" type="text" placeholder="Комментарий" class="text order_input" />
            <input class="comment_button" type="submit" value="Оставить комментарий">
        </form>
    </div>
</section>

Coffee/Views/Comment/Completed.cshtml
@{
    ViewData["Title"] = "Complete!!!";
    Layout = "~/Views/_Layout.cshtml";
}

<section class="order" id="order">
    <div class="container order_container">
        <img src="~/img/order_bg.jpg" alt="" class="orger_img">
        <div class="container"><p class="text banner_text">Ваш комментарий был успешно сохранен!!!</p></div>
    </div>
</section>

Coffee/Views/Home/CommentsPartial.cshtml
@model List<Comment>

@foreach (var item in Model)
{
    <div>
        <h3 class="heading swiper_heading">@item.Name</h3>
        <p class="text swiper_comment">@item.Text</p>
    </div>
}

Coffee/Views/Home/Completed.cshtml
@{
    ViewData["Title"] = "Complete!!!";
    Layout = "~/Views/_Layout.cshtml";
}

<section class="order" id="order">
    <div class="container order_container">
        <img src="~/img/order_bg.jpg" alt="" class="orger_img">
        <div class="container"><p class="text banner_text">Ваш заказ был успешно сохранен!!!</p></div>
    </div>
</section>

Coffee/Views/Home/Index.cshtml
@model Order
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coffee Step</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/modal.css">
    <link href="~/css/add-styles.css" rel="stylesheet" />
    
</head>

<body>
    <main>
        <div class="banner">
            <div class="container banner_container">
                <header class="header">
                    <div class="logo">
                        <img src="~/img/logo.png" alt="logo" class="logo">
                    </div>

                    <nav class="nav_list">
                        <img src="~/img/close.png" alt="" class="close">
                        <ul id="menu">
                            <li class="nav_item"><a href="#about">О нас</a></li>
                            <li class="nav_item"><a href="#design">Дизайн</a></li>
                            <li class="nav_item"><a href="#products">Ассортимент</a></li>
                            <li class="nav_item"><a href="#payment">Оплата и доставка</a></li>
                            <li class="nav_item"><a href="#comments">Отзывы</a></li>
                            <li class="nav_item"><a href="#contacts">Контакты</a></li>
                        </ul>
                    </nav>

                    <img src="~/img/hamburger.png" alt="" class="hamburger">

                </header>

                <section class="banner_content">
                    <h1 class="heading banner_heading">Кофе для тебя</h1>
                    <p class="text banner_text">
                        Бодрящий, ароматный напиток не оставит равнодушным даже самых больших
                        ценителей
                    </p>
                    <a href="#order" class="button banner_button">Заказать кофе</a>
                </section>
            </div>
        </div>

        <section class="about" id="about">
            <div class="container about_container">
                <h2 class="heading about_heading">О нас</h2>
                <div class="about_content">
                    <img src="~/img/about_bg.jpg" alt="about us" class="about_img">
                    <div class="about_info">
                        <h3 class="about_content_heading">Coffee Step</h3>
                        <p class="text about_text">
                            Является прекрасным местом, где можно не только приятно посидеть,
                            выпить
                            чашечку ароматного напитка или перекусить, но и купить кофе в зернах. Оформлена она бежевых
                            оттенках. Мебель порадует классическим исполнением. Большая
                            барная стойка позволит бариста продемонстрировать процесс приготовления кофе. Входя в
                            помещение,
                            начинаешь чувствовать невероятный, крепкий и устойчивый характерный аромат. Здесь предлагают
                            не
                            только горячие напитки, но и натуральные кофейные зёрна от лучших производителей.
                        </p>
                    </div>
                </div>
            </div>
        </section>

        <section class="design" id="design">
            <div class="container design_container">
                <h2 class="heading design_heading">Дизайн</h2>
                <div class="gallery">
                    <img src="~/img/design1.jpg" alt="design_photo" class="gallery_item">
                    <img src="~/img/design2.jpg" alt="design_photo" class="gallery_item">
                    <img src="~/img/desing4.jpg" alt="design_photo" class="gallery_item">
                    <img src="~/img/design3.jpg" alt="design_photo" class="gallery_item">
                    <img src="~/img/design_big.jpg" alt="design_photo" class="gallery_item">
                </div>
            </div>
        </section>

        <section class="products" id="products">
            <div class="container products_container">
                <h2 class="heading products_heading">Ассортимент</h2>
                <div class="products_cards_container">
                    <div class="product_card">
                        <img src="~/img/starbucks.png" alt="starbucks" class="product_img">
                        <div class="product_card_content">
                            <p class="text product_name">Кофе Starbucks Blonde</p>
                            <p class="text product_price">170 ₴</p>
                        </div>
                    </div>

                    <div class="product_card">
                        <img src="~/img/zhokey.png" alt="starbucks" class="product_img">
                        <div class="product_card_content">
                            <p class="text product_name">Кофе “Жокей”</p>
                            <p class="text product_price">140 ₴</p>
                        </div>
                    </div>

                    <div class="product_card">
                        <img src="~/img/ferarra.png" alt="starbucks" class="product_img">
                        <div class="product_card_content">
                            <p class="text product_name">Кофе Starbucks Blonde</p>
                            <p class="text product_price">170 ₴</p>
                        </div>
                    </div>

                    <div class="product_card">
                        <img src="~/img/ethiopia.png" alt="starbucks" class="product_img">
                        <div class="product_card_content">
                            <p class="text product_name">Кофе “Ethiopia”</p>
                            <p class="text product_price">166 ₴</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="payment" id="payment">
            <div class="container payment_container">
                <h2 class="heading payment_heading">Оплата и доставка</h2>
                <div class="payment_process">
                    <div class="process_card">
                        <h3 class="text process_heading">Заявка</h3>
                        <p class="text process_text">
                            Отправляем заявку на нашем сайте. Вся информация полностью
                            конфиденциальна.
                        </p>
                    </div>

                    <div class="process_card">
                        <h3 class="text process_heading">Звонок</h3>
                        <p class="text process_text">
                            Менеджер уточняет детали заказа. Вы получаете сообщение на email с
                            информацией о заказе.
                        </p>
                    </div>

                    <div class="process_card">
                        <h3 class="text process_heading">Доставка</h3>
                        <p class="text process_text">
                            Курьерская доставка заказа Новой почтой или же самовывоз из
                            кофейни.
                        </p>
                    </div>

                    <div class="process_card">
                        <h3 class="text process_heading">Оплата</h3>
                        <p class="text process_text">
                            Оплата банковской картой, наличными при получении, наложеный платеж
                            .
                        </p>
                    </div>
                </div>
            </div>
        </section>

        <section class="comments" id="comments">
            <div class="container comments_container">
                <h2 class="heading comments_heading">Отзывы</h2>

                <a class="comment_button" asp-controller="Comment" asp-action="Add">Оставить отзыв</a>
                <div class="margin-slider">
                    <div class="swiper">
                        <div class="swiper-wrapper">
                        </div>
                    </div>
                    <div class="swiper-navigation">
                        <button id="swiperPrev">&lt;</button>
                        <button id="swiperNext">&gt;</button>
                    </div>
                </div>
              


            </div>
        </section>
        <section class="order" id="order">
            <div class="container order_container">
                <img src="~/img/order_bg.jpg" alt="" class="orger_img">
                <form asp-controller="Home" asp-action="Checkout" method="post" class="order_form">
                    <h3 class="text order_form_heading">Оформить заказ</h3>
                    <span asp-validation-for="Name"></span>
                    <input asp-for="Name" type="text" placeholder="Имя" class="text order_input">
                    <span asp-validation-for="Phone"></span>
                    <input asp-for="Phone" type="number" placeholder="Номер телефона" class="text order_input">
                    <input class="comment_button" type="submit" value="Заказать кофе" data-btn="order">
                </form>
            </div>
        </section>


    </main>


    <footer class="footer" id="contacts">
        <div class="container footer_container">
            <div class="footer_info">
                <div class="footer_contacts">
                    <ul class="text footer_address">
                        <li class="footer_item">Харьков, ул. Пушкинская 13</li>
                        <li class="footer_item">Киев, проспект Свободы 45</li>
                        <li class="footer_item">Полтава, ул. Мирная 2</li>
                        <li class="footer_item">+ 380 (66) 649 74 25</li>
                        <li class="footer_item">coffeestep@gmail.com</li>
                    </ul>

                    <div class="footer_social">
                        <a href=""><img src="~/img/instagram.png" alt="" class="social_item"></a>
                        <a href=""><img src="~/img/facebook.png" alt="" class="social_item"></a>
                        <a href=""><img src="~/img/telegram.png" alt="" class="social_item"></a>
                    </div>
                </div>


                <p class="text footer_time">
                    Время работы<br>
                    ПН - ПТ 11:00 - 23:00<br>
                    СБ - ВС 11:00 - 21:00
                </p>
            </div>

            <img src="~/img/map.jpg" alt="" class="footer_img">
        </div>
    </footer>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
    <script src="~/js/swiper.js"></script>
    <script src="~/js/scroll.js"></script>
    <script src="~/js/menu.js"></script>
    @*<script src="~/js/modal.js"></script>*@
</body>

</html>

Coffee/Views/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/**/*.min.css" 
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link href="~/css/add-styles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>

<body>
    <main>
        <div class="banner">
            <div class="container banner_container">
                <header class="header">
                    <div class="logo">
                        <img src="~/img/logo.png" alt="logo" class="logo">
                    </div>

                    <nav class="nav_list">
                        <img src="~/img/close.png" alt="" class="close">
                        <ul id="menu">
                            <li class="nav_item"><a asp-controller="Home" asp-action="Index">На главную &#8594;</a></li>
                            @*<li class="nav_item"><a asp-controller="Home" asp-action="Index">Дизайн</a></li>
                            <li class="nav_item"><a asp-controller="Home" asp-action="Index">Ассортимент</a></li>
                            <li class="nav_item"><a asp-controller="Home" asp-action="Index">Оплата и доставка</a></li>
                            <li class="nav_item"><a asp-controller="Home" asp-action="Index">Отзывы</a></li>
                            <li class="nav_item"><a asp-controller="Home" asp-action="Index">Контакты</a></li>*@
                        </ul>
                    </nav>

                    <img src="~/img/hamburger.png" alt="" class="hamburger">

                </header>

            </div>
        </div>
        @RenderBody()
    </main>


    <footer class="footer" id="contacts">
        <div class="container footer_container">
            <div class="footer_info">
                <div class="footer_contacts">
                    <ul class="text footer_address">
                        <li class="footer_item">Харьков, ул. Пушкинская 13</li>
                        <li class="footer_item">Киев, проспект Свободы 45</li>
                        <li class="footer_item">Полтава, ул. Мирная 2</li>
                        <li class="footer_item">+ 380 (66) 649 74 25</li>
                        <li class="footer_item">coffeestep@gmail.com</li>
                    </ul>

                    <div class="footer_social">
                        <a href=""><img src="~/img/instagram.png" alt="" class="social_item"></a>
                        <a href=""><img src="~/img/facebook.png" alt="" class="social_item"></a>
                        <a href=""><img src="~/img/telegram.png" alt="" class="social_item"></a>
                    </div>
                </div>


                <p class="text footer_time">
                    Время работы
                    ПН - ПТ 11:00 - 23:00
                    СБ - ВС 11:00 - 21:00
                </p>
            </div>

            <img src="~/img/map.jpg" alt="" class="footer_img">
        </div>
    </footer>

</body>

</html>